version: '3.9'

services:
  rabbit:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - back
  app:
    build: .
    restart: always
    ports: 
    - 9600:9600
    depends_on:
      - rabbit
    networks:
      - back
networks:
  back:
    driver: bridge
    
